# Generated by Django 5.1.1 on 2024-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0004_alter_requisicoes_antenista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN')], default='', max_length=100),
        ),
    ]
