# Generated by Django 5.1.1 on 2024-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0016_alter_estoque_antenista_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
