# Generated by Django 5.1.1 on 2024-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0018_alter_requisicoes_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=180000, null=True),
        ),
    ]
