# Generated by Django 5.1.1 on 2024-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0020_alter_requisicoes_tipo_customizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
