# Generated by Django 5.1.1 on 2024-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0021_alter_requisicoes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
