# Generated by Django 5.1.1 on 2024-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0025_alter_requisicoes_antenista_alter_requisicoes_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='aos_cuidados',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
