# Generated by Django 5.1.1 on 2024-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0026_requisicoes_aos_cuidados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
