# Generated by Django 5.1.1 on 2024-10-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T42Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(choices=[('TETS', 'TETS'), ('TETS R', 'TETS R'), ('LOKIES', 'LOKIES')], max_length=100, null=True)),
                ('id_equipamento', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('', ''), ('Atualizado e Configurado', 'Atualizado e Configurado'), ('Não Atualizado', 'Não Atualizado'), ('Não Configurado', 'Não Configurado'), ('Manutenção', 'Manutenção')], max_length=50, null=True)),
                ('reversa', models.DateField(blank=True, null=True)),
                ('estoque_status', models.CharField(blank=True, choices=[('Estoque', 'Estoque'), ('Retornando', 'Retornando'), ('Enviado', 'Enviado'), ('Estraviado', 'Estraviado'), ('Manutenção', 'Manutenção')], max_length=50, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t42_nome', to='acompanhamento.clientes')),
            ],
        ),
    ]
