# Generated by Django 5.1.1 on 2024-10-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='estoque_status',
            field=models.CharField(blank=True, choices=[('Estoque', 'Estoque'), ('Retornando', 'Retornando'), ('Enviado', 'Enviado'), ('Estraviado', 'Estraviado'), ('Manutenção', 'Manutenção')], default='Estoque', max_length=50, null=True),
        ),
    ]
