# Generated by Django 5.1.1 on 2024-10-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='estoque_tuper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='formulario_divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportadora', models.CharField(blank=True, choices=[('Transportadora Peregrina', 'Transportadora Peregrina'), ('Valor Transportes', 'Valor Transportes'), ('transjk Transportes Rodoviarios', 'transjk Transportes Rodoviarios'), ('JVG Transportes', 'JVG Transportes'), ('JP Transportes', 'JP Transportes'), ('Cooperleste Cooperativa dos Transportes', 'Cooperleste Cooperativa dos Transportes'), ('Astran Transportes', 'Astran Transportes'), ('Asavel Transportes', 'Asavel Transportes'), ('AGR Transportes', 'AGR Transportes'), ('A.Alves Correa Ligeirinho Transportes', 'A.Alves Correa Ligeirinho Transportes'), ('Dolci & Dolci Transporte', 'Dolci & Dolci Transporte')], max_length=50, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('Id_equipamentos', models.TextField(blank=True, default='', max_length=250)),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtotuper', to='produto.produto')),
            ],
        ),
    ]
