# Generated by Django 5.1.1 on 2024-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], default='Pendente', max_length=50, null=True),
        ),
    ]
