# Generated by Django 5.1.1 on 2024-10-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_rename_transportadora_clientes_seguradora'),
        ('produto', '0001_initial'),
        ('registrodemanutencao', '0006_registrodemanutencao_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='criarlaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('motivo', models.CharField(blank=True, choices=[('', ''), ('Manutenção', 'Manutenção'), ('Devolução/Estoque', 'Devolução/Estoque')], max_length=50, null=True)),
                ('tipo_customizacao', models.CharField(blank=True, choices=[('', ''), ('Sem customização', 'Sem customização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)')], max_length=50, null=True)),
                ('id_equipamentos', models.TextField(blank=True, default='', max_length=1200)),
                ('faturamento', models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], default='Pendente', max_length=50, null=True)),
                ('tipo_problema', models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('USB Danificado', 'USB Danificado'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('USB Sem problemas Identificados', 'USB Sem problemas Identificados')], max_length=50, null=True)),
                ('tipo_entrada', models.CharField(blank=True, choices=[('Manutenção', 'Manutenção'), ('Devolução/Estoque', 'Devolução/Estoque')], max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, default='', max_length=250)),
                ('tratativa', models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('USB Danificado', 'USB Danificado'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('USB Sem problemas Identificados', 'USB Sem problemas Identificados')], max_length=50, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_nome', to='acompanhamento.clientes')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_produto', to='produto.produto')),
            ],
        ),
    ]
