# Generated by Django 5.1.1 on 2024-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0007_criarlaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarlaudo',
            name='id_manutenção',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
