# Generated by Django 5.1.1 on 2024-10-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0009_imagemregistro_laudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemregistro',
            name='laudo',
        ),
        migrations.DeleteModel(
            name='criarlaudo',
        ),
    ]
