# Generated by Django 5.1.1 on 2024-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0010_remove_imagemregistro_laudo_delete_criarlaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemregistro',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='imagemregistro',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
