# Generated by Django 5.1.1 on 2024-10-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0011_imagemregistro_imagem2_imagemregistro_imagem3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemregistro',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='imagemregistro',
            name='imagem3',
        ),
        migrations.RemoveField(
            model_name='registrodemanutencao',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='registrodemanutencao',
            name='imagem3',
        ),
    ]
