# Generated by Django 5.1.1 on 2024-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0012_remove_imagemregistro_imagem2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemregistro',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
