# Generated by Django 5.1.1 on 2024-10-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='inicio_de_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vigencia',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('12', '12'), ('24', '24'), ('36', '36'), ('48', '48')], max_length=50, null=True),
        ),
    ]
