# Generated by Django 5.1.1 on 2024-10-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_alter_clientes_inicio_de_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='transportadora',
            new_name='seguradora',
        ),
    ]
