# Generated by Django 5.1.1 on 2024-10-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(blank=True, max_length=255, null=True)),
                ('franquia_hora', models.CharField(blank=True, max_length=255, null=True)),
                ('franquia_km', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('prestador', models.CharField(choices=[('Sombra armado', 'Sombra armado')], max_length=50)),
                ('placa', models.CharField(max_length=255)),
                ('id_equipamento', models.CharField(max_length=255)),
                ('km_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('km_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedagio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(blank=True, default='Pendente', max_length=10, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacompanhamento.agentes')),
            ],
        ),
    ]
