# Generated by Django 5.1.1 on 2024-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paradasegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_renavan', models.CharField(blank=True, max_length=255, null=True)),
                ('insercao_tecnologia', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_carreta', models.CharField(blank=True, max_length=255, null=True)),
                ('data_reinicio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
