# Generated by Django 5.1.1 on 2024-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='cnh',
            new_name='descreva',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='data_reinicio',
            new_name='horario_saida',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='insercao_tecnologia',
            new_name='inconformidade',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='numero_renavan',
            new_name='nome_motorista',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='placa_carreta',
            new_name='placa_cavalo',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='placa_veiculo',
            new_name='previsao_saida',
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='embarcador',
            field=models.CharField(blank=True, choices=[('CORTEVA', 'CORTEVA'), ('BAYER', 'BAYER')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado',
            field=models.CharField(blank=True, choices=[('1017274', '1017274'), ('1017649', '1017649'), ('1017702', '1017702'), ('1017994', '1017994'), ('1018134', '1018134')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador',
            field=models.CharField(blank=True, choices=[('296832', '296832'), ('296849', '296849'), ('558949', '558949'), ('612622', '612622'), ('613796', '613796')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='tipo_posto',
            field=models.CharField(blank=True, default='Pendente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='transportador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
