# Generated by Django 5.1.1 on 2024-10-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0002_rename_cnh_paradasegura_descreva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='descreva',
            field=models.CharField(blank=True, choices=[('1017274', '1017274'), ('1017649', '1017649'), ('1017702', '1017702'), ('1017994', '1017994'), ('1018134', '1018134')], max_length=255, null=True),
        ),
    ]
