# Generated by Django 5.1.1 on 2024-10-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0004_alter_paradasegura_descreva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='horario_saida',
            new_name='Horario_saida',
        ),
    ]
