# Generated by Django 5.1.1 on 2024-10-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0005_rename_horario_saida_paradasegura_horario_saida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='Horario_saida',
            new_name='Horario_de_saida',
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='previsao_de_saida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='inconformidade',
            field=models.CharField(blank=True, choices=[('NÃO', 'NÃO'), ('SENSOR PORTA MOTORISTA', 'SENSOR PORTA MOTORISTA'), ('SENSOR PORTA PASSAGEIRO', 'SENSOR PORTA PASSAGEIRO'), ('TECLADO', 'TECLADO'), ('BOTAO DE PANICO', 'BOTAO DE PANICO'), ('LACRE BAU', 'LACRE BAU'), ('SIRENE', 'SIRENE'), ('BLOQUEIO', 'BLOQUEIO'), ('CHAVE GERAL', 'CHAVE GERAL'), ('CNH', 'CNH'), ('DOCUMENTO DO VEICULO', 'DOCUMENTO DO VEICULO'), ('DOCUMENTO DA CARRETA', 'DOCUMENTO DA CARRETA'), ('OUTROS', 'OUTROS')], max_length=255, null=True),
        ),
    ]
