# Generated by Django 5.1.1 on 2024-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0007_alter_paradasegura_descreva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='id_cadeado',
            field=models.CharField(blank=True, choices=[('1017242', '1017242'), ('1017287', '1017287'), ('1016690', '1016690'), ('1017601', '1017601'), ('1017716', '1017716')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='id_rastreador',
            field=models.CharField(blank=True, choices=[('1017242', '1017242'), ('1017287', '1017287'), ('1016690', '1016690'), ('1017601', '1017601'), ('1017716', '1017716')], max_length=255, null=True),
        ),
    ]
