# Generated by Django 5.1.1 on 2024-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0010_alter_paradasegura_id_cadeado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='id_cadeado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='id_rastreador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='tipo_posto',
            field=models.CharField(blank=True, choices=[('1', 'POSTO DA SERRA'), ('2', 'POSTO BURITIZINHO'), ('3', 'POSTO BRASILEIRÃO'), ('4', 'POSTO TREVÃO'), ('5', 'POSTO JN'), ('6', 'POSTO CAPIXABOM'), ('7', 'POSTO GRAAL RUBI')], default='Pendente', max_length=255, null=True),
        ),
    ]
