# Generated by Django 5.1.1 on 2024-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0014_remove_paradasegura_id_cadeado2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_cadeado7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='id_rastreador7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
