# Generated by Django 5.1.1 on 2024-10-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0015_paradasegura_id_cadeado2_paradasegura_id_cadeado3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='id_cadeado1',
            new_name='id_cadeado',
        ),
        migrations.RenameField(
            model_name='paradasegura',
            old_name='id_cadeado2',
            new_name='id_rastreador',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_cadeado3',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_cadeado4',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_cadeado5',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_cadeado6',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_cadeado7',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador1',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador2',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador3',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador4',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador5',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador6',
        ),
        migrations.RemoveField(
            model_name='paradasegura',
            name='id_rastreador7',
        ),
    ]
