# Generated by Django 5.1.1 on 2024-10-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0016_rename_id_cadeado1_paradasegura_id_cadeado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='placa_carreta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
