# Generated by Django 5.1.1 on 2024-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0017_paradasegura_placa_carreta'),
    ]

    operations = [
        migrations.CreateModel(
            name='passagemmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pa', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_do_posto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('Iscas', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('notebook', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('celular', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('antena', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('bodycam', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('cadeados', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('drone', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('descrição', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('fotos', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
            ],
        ),
    ]
