# Generated by Django 5.1.1 on 2024-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0021_alter_passagemmodel_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagemmodel',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
