# Generated by Django 5.1.1 on 2024-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0027_paradasegura_tipo_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='nome_do_pa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='tipo_parada',
            field=models.CharField(blank=True, choices=[('Pernoite', 'Pernoite'), ('Refeição', 'Refeição'), ('Check List', 'Check List')], max_length=255, null=True),
        ),
    ]
