# Generated by Django 5.1.1 on 2024-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(choices=[('Selecione o Status', 'Selecione o Status'), ('Não Faturado', 'Não Faturado'), ('Faturado', 'Faturado'), ('Pendente', 'Pendente')], default='', max_length=20),
        ),
    ]
