# Generated by Django 5.1.1 on 2024-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiccid',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
