# Generated by Django 5.1.1 on 2024-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0003_alter_reativacao_status_reativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiccid',
            name='iccids_criados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idiccid',
            name='total_iccids',
            field=models.IntegerField(default=0),
        ),
    ]
