# Generated by Django 5.1.1 on 2024-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0004_idiccid_iccids_criados_idiccid_total_iccids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiccid',
            name='iccids_criados',
        ),
        migrations.RemoveField(
            model_name='idiccid',
            name='total_iccids',
        ),
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(choices=[('', 'Selecione o Status'), ('Vazio', 'Vazio'), ('faturado', 'Faturado')], default='', max_length=10),
        ),
    ]
