# Generated by Django 5.1.1 on 2024-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0005_remove_idiccid_iccids_criados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reativacao',
            name='motivo_reativacao',
            field=models.CharField(blank=True, choices=[('', 'Selecione o Status'), ('Vazio', 'Vazio'), ('Faturado', 'Faturado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(choices=[('Faturado', 'Faturado'), ('Não Faturado', 'Não Faturado')], default='', max_length=100),
        ),
    ]
