# Generated by Django 5.1.1 on 2024-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0006_alter_reativacao_motivo_reativacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reativacao',
            name='motivo_reativacao',
            field=models.CharField(blank=True, choices=[('', 'Selecione o Motivo'), ('Vazio', 'Vazio'), ('Faturado', 'Faturado')], max_length=50, null=True),
        ),
    ]
