# Generated by Django 5.1.1 on 2024-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=255, null=True),
        ),
    ]
