# Generated by Django 5.1.1 on 2024-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=255, null=True),
        ),
    ]
