# Generated by Django 5.1.1 on 2024-10-15 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticketmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='setor',
            field=models.CharField(blank=True, choices=[('Diretoria', 'Diretoria'), ('Inteligência', 'Inteligência'), ('Faturamento', 'Faturamento'), ('Expedição', 'Expedição'), ('Configuração', 'Configuração'), ('Quality', 'Quality'), ('Area Técnica', 'Area Técnica'), ('Comercial', 'Comercial')], max_length=255, null=True),
        ),
    ]
